name: Commitlint (prlint)
author: Kevin Taeyoon Jin <hello@kevintyj.com>
description: Ensure PR title match commitlint config
runs:
  using: node20
  main: dist/index.js
inputs:
  cl-config:
    description: Path to commit lint config (commitlint.config.js)
    default: commitlint.config.js
    required: false
  useDescription:
    description: if to take into account the description of the PR too when validating
    default: 'false'
    required: false
  convertToCJS:
    description: if to convert the config to CJS before using it
    default: 'false'
    required: false
outputs:
  lint-status:
    description: The status of the PR lint
  lint-details:
    description: The output of the PR lint from commitlint
branding:
  icon: git-pull-request
  color: green
